### ISSUE TITLE
Could not initialize class org.codhaus.groovy.vmplugin.v7.Java7

### ISSUE THREAD

**Issue by Flameopathic** [ExtraCrafTX/GeneratorFabricMod#10]
This error comes up after successfully creating a project folder with GeneratorFabricMod. According to what the internet says, this is a problem that the newest version of Gradle fixes. However, v0.1.1 of GeneratorFabricMod is using Gradle version 5.5.1 instead of 6.3. I have tried switching Java versions and v0.1.2 does not work due to the Java version issue that others have mentioned.

**Comment by ExtraCrafTX** [comment]
Could you post a full log?

**Comment by Flameopathic** [comment]
I'm sorry, I'm new to this. How do I use a paste service and what is it?

**Comment by ExtraCrafTX** [comment]
No worries, glad it got sorted 👍
