### ISSUE TITLE
there is no bin folder

### ISSUE THREAD

**Issue by z3roco01** [ExtraCrafTX/GeneratorFabricMod#18]
i go to to THE ```$ export PATH=$PATH:/your/chosen/folder/GeneratorFabricMod/bin``` command and it doesnt say any errors but i cant run the ```$ GeneratorFabricMod``` command then i check the folder and theres no bin folder

**Comment by ExtraCrafTX** [comment]
You should make sure that you unpack the archive correctly, and that you are downloading a release archive and not the source code.
If neither of these solves the issue, please send a screenshot of the downloaded archive and the folder where you extracted it.

**Comment by z3roco01** [comment]
thanks
