### ISSUE TITLE
Support for older minecraft version

### ISSUE THREAD

**Issue by Maratonec** [ExtraCrafTX/GeneratorFabricMod#19]
Is it possible to add support for older versions? I think many would appreciate 1.8.9 support, because it is the most used version for pvp

**Comment by TheAwesome98-Real** [comment]
but fabric is not compatible for 1.8.9..?

**Comment by ExtraCrafTX** [comment]
Yeah, as mentioned, this is specifically for fabric mods, so support for older versions is not something that will be added here.
