### ISSUE TITLE
gradlew sh script not marked as executable

### ISSUE THREAD

**Issue by MinusGix** [ExtraCrafTX/GeneratorFabricMod#3]
The `gradlew` sh script (the file just named `gradlew`, not `gradlew.bat`) is not marked as executable, which on Linux will mean you aren't allowed to execute it.  
This is fairly simple to fix for the user, and non-major (I just need to run `chmod +x ./gradlew` to mark it as executable), but it would be nicer if it could be setup properly out of the box.

**Comment by ExtraCrafTX** [comment]
Is this in regards to the `gradlew` used to run the generator itself, or the `gradlew` output by the generator? It may very well be both. I will take a look today, I don't tend to use Linux too often so haven't noticed.

**Comment by ExtraCrafTX** [comment]
Just confirmed, carried over from [TemplateMakerFabric](https://github.com/ExtraCrafTX/TemplateMakerFabric/). Opening an issue there now.
