### ISSUE TITLE
Gradle version differing from example mod

### ISSUE THREAD

**Issue by MinusGix** [ExtraCrafTX/GeneratorFabricMod#4]
Don't know if this is issue worthy, but it felt like a better method than pinging you on Discord.  
The gradle version used by this generator is older (4.10.3) than the current version used by the fabric example mod (5.5.1) which was changed in this commit: https://github.com/FabricMC/fabric-example-mod/commit/01bf2f5a56646852cfee359bd939bb193e22d7f7  
(Also, this program itself uses gradle version 6.0.1, though that matters less since most will use the release)  
It would probably be a good idea to follow the main example's lead on the gradle version. If it wasn't followed, then you may get issues where confusion arises over available gradle features. Also the downside of having yet another gradle version to install.

**Comment by ExtraCrafTX** [comment]
The program includes 2 versions of Gradle, 4.10.3 and 5.5.1. If the loom version used is > 0.2.5, it should automatically output 5.5.1.

I will test this again today. Thanks, and feel free to ping me on discord too.

**Comment by ExtraCrafTX** [comment]
Also, this is an issue carried over from [TemplateMakerFabric](https://github.com/ExtraCrafTX/TemplateMakerFabric), would appreciate it if you could open an issue there too.

**Comment by ExtraCrafTX** [comment]
Found the issue, carried over from [TemplateMakerFabric](https://github.com/ExtraCrafTX/TemplateMakerFabric/). Opening an issue there now.
