### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by DragoSpiro98** [ExtraCrafTX/GeneratorFabricMod#8]
When I launch the application it gives this error

> Error: A JNI error has occurred, please check your installation and try again
> Exception in thread "main" java.lang.UnsupportedClassVersionError: com/extracraftx/minecraft/generatorfabricmod/GeneratorFabricMod has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(Unknown Source)
>         at java.security.SecureClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.access$100(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

I have Java 8 version 251 on Windows 10

**Comment by ExtraCrafTX** [comment]
Duplicate of #5

The latest version requires Java 9. This is an error and will be resolved soon, but in the meantime you can simply use 0.1.1 instead, it is the same feature wise.

**Comment by DragoSpiro98** [comment]
Thanks
