### ISSUE TITLE
Problem reported when sources are generated

### ISSUE THREAD

**Issue by Flameopathic** [ExtraCrafTX/GeneratorFabricMod#9]
After generating sources in VS Code, this error message comes out:
{
	"resource": "/D:/Java Workspace/Food Overhaul 1.15.2/",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "0",
	"severity": 8,
	"message": "Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-5.5.1-bin.zip'.\r\nCould not open cp_init remapped class cache for 6a5krabdzij62jglcll542e66 (C:\\Users\\name\\.gradle\\caches\\5.5.1\\scripts-remapped\\eclipsePlugin_6l67cfs5tyergoy72d0aq27th\\6a5krabdzij62jglcll542e66\\cp_init607e3b0704a468e3ccebfac8f1ad43c0).\r\nCould not open cp_init generic class cache for initialization script 'C:\\Users\\name\\AppData\\Roaming\\Code\\User\\workspaceStorage\\b855420ddcfbf72272d1a21dc84fffd3\\redhat.java\\jdt_ws\\.metadata\\.plugins\\org.eclipse.buildship.core\\init.d\\eclipsePlugin.gradle' (C:\\Users\\name\\.gradle\\caches\\5.5.1\\scripts\\6a5krabdzij62jglcll542e66\\cp_init\\cp_init607e3b0704a468e3ccebfac8f1ad43c0).\r\nCould not initialize class org.codehaus.groovy.classgen.Verifier",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
I am using v0.1.1 because v0.1.2 has the java errors that others report.
Please advise

Edit: I don't know if this means anything, but the Gradle version seems to be outdated in v0.1.1. In 0.1.1, the gradle version is 5.5.1, while the newest version of gradle is 6.3.

**Comment by ExtraCrafTX** [comment]
The gradle version is not an issue. This seems like a potential configuration issue on your end. It is a very weird issue, I haven't seen anything like it before.

Does this happen with a project created without GeneratorFabricMod (the [example mod](https://github.com/FabricMC/fabric-example-mod) for instance)?

There are a few things you can try:
1. Ensure that you have the Java extension pack installed and up to date
2. Try to clean the java workspace (Ctrl+Shift+P, then type "clean java" and a command should come up saying "Clean java language server workspace" or something similar)
3. Try deleting `C:\Users\name\.gradle\caches\5.5.1` and deleting the `.gradle` folder in your project directory
4. Try starting from a clean project, following steps on the fabric wiki exactly

Hopefully one or more of these steps will solve the issue. If not, please outline the exact steps you took in as much detail as possible.

**Comment by Flameopathic** [comment]
The problem did not occur in the example mod, and when I switched IDEs(VS Code to Intellij IDEA) and made sure that everything was being made from scratch, it ended up working. Thank you!
